// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DictEntryDefine {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DictEntryDelete {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
/// pos_list is used to indicate where dynamic values should be inserted
/// it's more accurate than a marker
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PatternDefine {
    #[prost(uint64, tag = "1")]
    pub pattern_id: u64,
    #[prost(string, tag = "2")]
    pub template: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub param_count: u32,
    #[prost(uint32, repeated, tag = "4")]
    pub pos_list: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PatternUpdate {
    #[prost(uint64, tag = "1")]
    pub pattern_id: u64,
    #[prost(string, tag = "2")]
    pub new_template: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub param_count: u32,
    #[prost(uint32, repeated, tag = "4")]
    pub pos_list: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PatternDelete {
    #[prost(uint64, tag = "1")]
    pub pattern_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
    #[prost(oneof = "log::Content", tags = "2, 3")]
    pub content: ::core::option::Option<log::Content>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "2")]
        Structured(super::StructuredLog),
        #[prost(string, tag = "3")]
        Raw(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredLog {
    #[prost(uint64, tag = "1")]
    pub pattern_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub dynamic_values: ::prost::alloc::vec::Vec<DynamicValue>,
}
/// TODO not sure we need numeric type
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicValue {
    #[prost(oneof = "dynamic_value::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<dynamic_value::Value>,
}
/// Nested message and enum types in `DynamicValue`.
pub mod dynamic_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        IntValue(i64),
        #[prost(double, tag = "2")]
        FloatValue(f64),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(uint64, tag = "4")]
        DictIndex(u64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Datum {
    #[prost(oneof = "datum::Data", tags = "1, 2, 3, 4, 5, 6")]
    pub data: ::core::option::Option<datum::Data>,
}
/// Nested message and enum types in `Datum`.
pub mod datum {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        PatternDefine(super::PatternDefine),
        #[prost(message, tag = "2")]
        PatternUpdate(super::PatternUpdate),
        #[prost(message, tag = "3")]
        PatternDelete(super::PatternDelete),
        #[prost(message, tag = "4")]
        DictEntryDefine(super::DictEntryDefine),
        #[prost(message, tag = "5")]
        DictEntryDelete(super::DictEntryDelete),
        #[prost(message, tag = "6")]
        Logs(super::Log),
    }
}
/// data is sequence of pattern/dictionary changes + logs
/// the ordering is significant, must be processed in order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatefulBatch {
    #[prost(uint32, tag = "1")]
    pub batch_id: u32,
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<Datum>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BatchStatus {
    #[prost(int32, tag = "1")]
    pub batch_id: i32,
    #[prost(enumeration = "batch_status::Status", tag = "2")]
    pub status: i32,
}
/// Nested message and enum types in `BatchStatus`.
pub mod batch_status {
    /// See Status Code Mappings section below for more details
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unknown = 0,
        Ok = 1,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Ok => "OK",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "OK" => Some(Self::Ok),
                _ => None,
            }
        }
    }
}
/// Generated client implementations.
pub mod stateful_logs_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct StatefulLogsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StatefulLogsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StatefulLogsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StatefulLogsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StatefulLogsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn logs_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::StatefulBatch>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::BatchStatus>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/intake.StatefulLogsService/LogsStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("intake.StatefulLogsService", "LogsStream"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod stateful_logs_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StatefulLogsServiceServer.
    #[async_trait]
    pub trait StatefulLogsService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the LogsStream method.
        type LogsStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::BatchStatus, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn logs_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::StatefulBatch>>,
        ) -> std::result::Result<tonic::Response<Self::LogsStreamStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct StatefulLogsServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StatefulLogsServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StatefulLogsServiceServer<T>
    where
        T: StatefulLogsService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/intake.StatefulLogsService/LogsStream" => {
                    #[allow(non_camel_case_types)]
                    struct LogsStreamSvc<T: StatefulLogsService>(pub Arc<T>);
                    impl<
                        T: StatefulLogsService,
                    > tonic::server::StreamingService<super::StatefulBatch>
                    for LogsStreamSvc<T> {
                        type Response = super::BatchStatus;
                        type ResponseStream = T::LogsStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::StatefulBatch>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StatefulLogsService>::logs_stream(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogsStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for StatefulLogsServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "intake.StatefulLogsService";
    impl<T> tonic::server::NamedService for StatefulLogsServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
