// This file is @generated by prost-build.
/// One HTTP request captured by lading's HTTP blackhole. The record's
/// `payload` is the decoded request body; `content_type` and `request_path`
/// describe what the target claimed to be sending on this request.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlackholeCaptureRecord {
    /// Milliseconds since the blackhole server started serving.
    #[prost(uint64, tag = "1")]
    pub relative_ms: u64,
    /// Size of the compressed (on-wire) request body in bytes, before the
    /// blackhole applied Content-Encoding decoding. Informational.
    #[prost(uint64, tag = "2")]
    pub compressed_bytes: u64,
    /// Value of the request's Content-Type header. Empty if absent.
    #[prost(string, tag = "3")]
    pub content_type: ::prost::alloc::string::String,
    /// Path portion of the request URI (e.g. "/api/v2/logs").
    #[prost(string, tag = "4")]
    pub request_path: ::prost::alloc::string::String,
    /// Decoded request body. If the request carried Content-Encoding (gzip,
    /// deflate, zstd), this field is the decompressed body.
    #[prost(bytes = "bytes", tag = "5")]
    pub payload: ::prost::bytes::Bytes,
}
