worker_threads = 3

[targets.simple]
target_uri = "http://localhost:8080/hi"
bytes_per_second = "3 Mb"
method.type = "Post"
method.variant = "DatadogLog"
method.maximum_prebuild_cache_size_bytes = "60 Mb"

[targets.simple.headers]
foo = "bar"