data_dir = "/var/lib/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.socket_source]
type = "socket"
address = "0.0.0.0:8282"
mode = "tcp"

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"

[sinks.socket_sink]
type = "socket"
inputs = ["socket_source"]
mode = "tcp"
address = "localhost:8080"
encoding = "json"
