//! Datadog Agent configuration template builders.
//!
//! Generates the YAML configuration files needed to run the agent with
//! the correct settings for each test scenario.

use std::path::Path;

/// Errors from configuration generation.
#[derive(thiserror::Error, Debug)]
pub enum Error {
    /// I/O error writing config files.
    #[error("config I/O error: {0}")]
    Io(#[from] std::io::Error),
}

/// Log source configuration variant.
#[derive(Debug, Clone)]
pub enum LogSourceConfig {
    /// Simple file tailing with no special processing.
    Simple,
    /// Auto multiline detection enabled.
    AutoMultiline,
    /// Explicit multiline pattern.
    ExplicitMultiline {
        /// Regex pattern that starts a new logical log entry.
        pattern: String,
    },
    /// Auto multiline with JSON detection and aggregation enabled.
    JsonMultiline,
    /// Adaptive sampling enabled with configurable parameters.
    AdaptiveSampling {
        /// Initial credits per pattern and credit cap.
        burst_size: f64,
        /// Credits refilled per second per pattern.
        rate_limit: f64,
    },
}

/// Parameters for generating agent configuration.
#[derive(Debug, Clone)]
pub struct AgentConfigParams {
    /// Port of the log intake server.
    pub intake_port: u16,
    /// Path where log files will be written (inside the container or on host).
    pub log_file_path: String,
    /// Whether to enable compression on the intake connection.
    pub use_compression: bool,
    /// Batch wait time in milliseconds (lower = faster drain).
    pub batch_wait_ms: u64,
    /// Log source configuration.
    pub log_source_config: LogSourceConfig,
    /// Maximum message size in bytes (for truncation testing).
    /// If `None`, uses the agent's default (256 KB).
    pub max_message_size_bytes: Option<usize>,
}

/// Write agent configuration files to the given directory.
///
/// Creates:
/// - `datadog.yaml` — main agent config
/// - `conf.d/proptest.d/conf.yaml` — log source config
///
/// # Errors
///
/// Returns error if file I/O fails.
#[expect(clippy::too_many_lines)]
pub fn write_agent_config(config_dir: &Path, params: &AgentConfigParams) -> Result<(), Error> {
    // Write main datadog.yaml
    let datadog_yaml = format!(
        r#"# Generated by lading_proptest
api_key: fake_key_for_proptest
hostname: lading-proptest

# Point all non-logs telemetry at a dead endpoint so the agent
# does not make outbound requests to datadoghq.com.
dd_url: "http://localhost:1"

logs_enabled: true
enable_metadata_collection: false
inventories_enabled: false

logs_config:
  logs_dd_url: "127.0.0.1:{intake_port}"
  logs_no_ssl: true
  force_use_http: true
  use_compression: {use_compression}
  batch_wait: {batch_wait}
  batch_max_size: 100
  open_files_limit: 100
  max_message_size_bytes: {max_message_size_bytes}
{adaptive_sampling_config}
apm_config:
  enabled: false

process_config:
  process_collection:
    enabled: false

security_agent:
  runtime_security_config:
    enabled: false

compliance_config:
  enabled: false
"#,
        intake_port = params.intake_port,
        use_compression = params.use_compression,
        batch_wait = params.batch_wait_ms,
        max_message_size_bytes = params.max_message_size_bytes.unwrap_or(256 * 1024),
        adaptive_sampling_config = match &params.log_source_config {
            LogSourceConfig::AdaptiveSampling { burst_size, rate_limit } => {
                format!(
                    "  experimental_adaptive_sampling:\n    enabled: true\n    burst_size: {burst_size}\n    rate_limit: {rate_limit}\n    protect_important_logs: false\n"
                )
            }
            _ => String::new(),
        },
    );

    std::fs::write(config_dir.join("datadog.yaml"), datadog_yaml)?;

    // Write log source config
    let conf_d = config_dir.join("conf.d").join("proptest.d");
    std::fs::create_dir_all(&conf_d)?;

    let log_source = match &params.log_source_config {
        LogSourceConfig::Simple => {
            format!(
                r#"logs:
  - type: file
    path: "{log_path}"
    service: proptest
    source: proptest
"#,
                log_path = params.log_file_path,
            )
        }
        LogSourceConfig::AutoMultiline => {
            format!(
                r#"logs:
  - type: file
    path: "{log_path}"
    service: proptest
    source: proptest
    auto_multi_line_detection: true
"#,
                log_path = params.log_file_path,
            )
        }
        LogSourceConfig::ExplicitMultiline { pattern } => {
            format!(
                r#"logs:
  - type: file
    path: "{log_path}"
    service: proptest
    source: proptest
    log_processing_rules:
      - type: multi_line
        name: proptest_multiline
        pattern: '{pattern}'
"#,
                log_path = params.log_file_path,
            )
        }
        LogSourceConfig::JsonMultiline => {
            format!(
                r#"logs:
  - type: file
    path: "{log_path}"
    service: proptest
    source: proptest
    auto_multi_line_detection: true
    auto_multi_line:
      enable_json_detection: true
      enable_json_aggregation: true
"#,
                log_path = params.log_file_path,
            )
        }
        LogSourceConfig::AdaptiveSampling { .. } => {
            format!(
                "logs:\n  - type: file\n    path: \"{log_path}\"\n    service: proptest\n    source: proptest\n    experimental_adaptive_sampling:\n      enabled: true\n",
                log_path = params.log_file_path,
            )
        }
    };

    std::fs::write(conf_d.join("conf.yaml"), log_source)?;

    Ok(())
}
