name: 'Install Protobuf'
description: 'Installs Protobuf compiler based on the runner OS'
runs:
  using: 'composite'
  steps:
    - run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
        elif [ "${{ runner.os }}" == "macOS" ]; then
          brew install protobuf
        elif [ "${{ runner.os }}" == "Windows" ]; then
          choco install protoc
        fi
      shell: bash
