[package]
name = "lading-antithesis"
version = "0.1.0"
authors = [
  "Brian L. Troutwine <brian.troutwine@datadoghq.com>",
  "George Hahn <george.hahn@datadoghq.com",
]
edition = "2024"
license = "MIT"
repository = "https://github.com/datadog/lading/"
keywords = ["random_test", "generator"]
categories = ["development-tools::profiling"]
description = "A tool for load testing daemons."

[features]
antithesis = ["dep:antithesis_sdk", "antithesis_sdk/full", "dep:serde_json"]

[dependencies]
antithesis_sdk = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[lib]
doctest = false

[lints]
workspace = true
